// Copyright (c) 2026 Arsenii Kvachan
// SPDX-License-Identifier: MIT

package hirevec

import (
	"errors"
)

var (
	ErrAboutForbiddenChars            = errors.New("about contains forbidden characters")
	ErrAboutTooLong                   = errors.New("about too long")
	ErrAboutTooShort                  = errors.New("about too short")
	ErrDescriptionRequired            = errors.New("description required")
	ErrEmailNotVerified               = errors.New("email not verified")
	ErrExtraDataDecoded               = errors.New("extra data decoded")
	ErrFailedAddRoutes                = errors.New("failed to add routes")
	ErrFailedAssembleRouteTree        = errors.New("failed to assemble route tree")
	ErrFailedBindAddress              = errors.New("failed to bind address")
	ErrFailedConnectDB                = errors.New("failed to connect to database")
	ErrFailedCreateAccessToken        = errors.New("failed to create access token")
	ErrFailedCreateAppleOIDCProvider  = errors.New("failed to create Apple OIDC provider")
	ErrFailedCreateGoogleOIDCProvider = errors.New("failed to create Google OIDC provider")
	ErrFailedCreateRefreshToken       = errors.New("failed to create refresh token")
	ErrFailedDecode                   = errors.New("failed to decode")
	ErrFailedExchangeToken            = errors.New("failed to exchange tokens")
	ErrFailedGenerateUsernameSuffix   = errors.New("failed to generate random username suffix")
	ErrFailedLoadAsymmetricKey        = errors.New("failed to load asymmetric key")
	ErrFailedLoadSymmetricKey         = errors.New("failed to load symmetric key")
	ErrFailedParseClaims              = errors.New("failed to parse claims")
	ErrFailedParseJTI                 = errors.New("failed to parse jti")
	ErrFailedParseLimit               = errors.New("invalid limit")
	ErrFailedParseOffset              = errors.New("invalid offset")
	ErrFailedParseProvider            = errors.New("failed to parse provider")
	ErrFailedParseScope               = errors.New("failed to parse scope")
	ErrFailedParseSerialID            = errors.New("invalid id")
	ErrFailedParseTokenType           = errors.New("failed to parse token type")
	ErrFailedParseUserID              = errors.New("failed to parse user id")
	ErrFailedSetProvider              = errors.New("failed to set provider")
	ErrFailedSetScope                 = errors.New("failed to set scope")
	ErrFailedSetTokenType             = errors.New("failed to set token type")
	ErrFailedShutdownServer           = errors.New("failed to shutdown server")
	ErrHandlerRequired                = errors.New("handler required")
	ErrIDTokenRequired                = errors.New("id_token required")
	ErrInvalidAccessToken             = errors.New("invalid access token")
	ErrInvalidID                      = errors.New("invalid id")
	ErrInvalidIDToken                 = errors.New("invalid id_token")
	ErrInvalidProvider                = errors.New("invalid provider")
	ErrInvalidRefreshToken            = errors.New("invalid refresh token")
	ErrInvalidRole                    = errors.New("invalid role")
	ErrInvalidSubject                 = errors.New("invalid subject")
	ErrInvalidTokenType               = errors.New("invalid token type")
	ErrNameForbiddenChars             = errors.New("name contains forbidden characters")
	ErrNameTooLong                    = errors.New("name too long")
	ErrNameTooShort                   = errors.New("name too short")
	ErrFullNameRequired               = errors.New("fullName required")
	ErrUserNameRequired               = errors.New("userName required")
	ErrUserNoRole                     = errors.New("user has no role")
	ErrUserNotFound                   = errors.New("user not found")
	ErrInvalidScopeValueType          = errors.New("invalid scope value type provided")
	ErrRecommendationExists           = errors.New("recommendation already exists")
	ErrCandidateNotFound              = errors.New("candidate not found")
)
